import { useState, type ComponentType } from "react";
import { ArrowLeft, BarChart3, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, Contact, LayoutDashboard, Menu, MessageCircle, Plus, Scissors, Search, Settings, Sparkles, TrendingUp, UserRound, UsersRound, WalletCards, X, Zap } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";

type View="dashboard"|"agenda"|"clientes"|"atendimentos"|"crm"|"servicos"|"equipe"|"relatorios";
type Status="AGENDADO"|"CONFIRMADO"|"EM ATENDIMENTO"|"REALIZADO"|"CANCELADO"|"NÃO COMPARECEU";
type Apt={id:number;time:string;client:string;service:string;barber:string;duration:string;value:string;payment:string;status:Status};
type Client={name:string;phone:string;last:string;frequency:string;ticket:string;status:string;since:string;initials:string};
const nav:{id:View;label:string;icon:ComponentType<{className?:string}>}[]=[
 ["dashboard","Dashboard",LayoutDashboard],["agenda","Agenda",CalendarDays],["clientes","Clientes",Contact],["atendimentos","Atendimentos",Scissors],["crm","CRM",TrendingUp],["servicos","Serviços",WalletCards],["equipe","Equipe",UsersRound],["relatorios","Relatórios",BarChart3],
].map(([id,label,icon])=>({id:id as View,label:label as string,icon:icon as ComponentType<{className?:string}>}));
const initial:Apt[]=[
 {id:1,time:"09:00",client:"João Reis",service:"Corte + Barba",barber:"Lucas",duration:"60 min",value:"R$ 150",payment:"Crédito",status:"CONFIRMADO"},{id:2,time:"10:00",client:"Fabio Copola",service:"Corte",barber:"Rafael",duration:"45 min",value:"R$ 85",payment:"Pix",status:"EM ATENDIMENTO"},{id:3,time:"11:30",client:"Guilherme Amaral",service:"Corte + Barba",barber:"Lucas",duration:"60 min",value:"R$ 150",payment:"Débito",status:"AGENDADO"},{id:4,time:"13:30",client:"Marcos Oliveira",service:"Barboterapia",barber:"Rafael",duration:"50 min",value:"R$ 135",payment:"Pix",status:"CONFIRMADO"},{id:5,time:"15:00",client:"Pedro Henrique",service:"Corte",barber:"Lucas",duration:"45 min",value:"R$ 85",payment:"Crédito",status:"AGENDADO"},{id:6,time:"16:30",client:"André Martins",service:"Skin Care",barber:"Diego",duration:"40 min",value:"R$ 80",payment:"Pix",status:"REALIZADO"}];
const clients:Client[]=[
 ["João Reis","(11) 98842-••••","12/09/2026","A cada 30 dias","R$ 145","Retorno próximo","Jan/2026","JR"],["Fabio Copola","(11) 97731-••••","24/09/2026","A cada 21 dias","R$ 92","Ativo","Mar/2026","FC"],["Guilherme Amaral","(11) 96520-••••","28/08/2026","A cada 35 dias","R$ 138","Em risco","Fev/2026","GA"],["Marcos Oliveira","(11) 95419-••••","19/09/2026","A cada 30 dias","R$ 121","Ativo","Abr/2026","MO"],["Pedro Henrique","(11) 94308-••••","15/09/2026","A cada 25 dias","R$ 96","Ativo","Mai/2026","PH"]
].map(x=>({name:x[0],phone:x[1],last:x[2],frequency:x[3],ticket:x[4],status:x[5],since:x[6],initials:x[7]}));
const services=[["Corte","R$ 85","45 min"],["Barba","R$ 75","35 min"],["Barboterapia","R$ 135","50 min"],["Combo Corte + Barba","R$ 150","60 min"],["Combo Corte + Barboterapia","R$ 200","75 min"],["Skin Care","R$ 80","40 min"],["Hidratação","R$ 50","30 min"],["Química","R$ 135","60 min"]];
const chart=[{day:"Sex",value:1680},{day:"Sáb",value:2450},{day:"Dom",value:0},{day:"Seg",value:1920},{day:"Ter",value:2180},{day:"Qua",value:1740},{day:"Hoje",value:1280}];
const tone:Record<Status,string>={"AGENDADO":"bg-info/10 text-info","CONFIRMADO":"bg-primary/10 text-primary","EM ATENDIMENTO":"bg-warning/10 text-warning","REALIZADO":"bg-secondary/10 text-secondary","CANCELADO":"bg-destructive/10 text-destructive","NÃO COMPARECEU":"bg-muted text-muted-foreground"};
function Badge({s}:{s:Status}){return <span className={cn("rounded-full px-2.5 py-1 text-[9px] font-bold whitespace-nowrap",tone[s])}>{s}</span>}
function Panel(p:{children:React.ReactNode;className?:string}){return <section className={cn("rounded-lg border border-border bg-card p-4 shadow-sm transition-colors hover:border-primary/20 md:p-5",p.className)}>{p.children}</section>}
function Heading({title,sub,action}:{title:string;sub?:string;action?:React.ReactNode}){return <div className="mb-5 flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{title}</h2>{sub&&<p className="mt-1 text-xs text-muted-foreground">{sub}</p>}</div>{action}</div>}
function Metric({label,value,icon:Icon,detail}:{label:string;value:string;icon:ComponentType<{className?:string}>;detail:string}){return <Panel><div className="flex justify-between text-xs text-muted-foreground"><span>{label}</span><span className="grid h-8 w-8 place-items-center rounded-md bg-accent text-primary"><Icon/></span></div><p className="mt-5 text-2xl font-semibold">{value}</p><p className="mt-2 text-[10px] text-muted-foreground">{detail}</p></Panel>}
function Chart(){return <div className="h-56"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="fill" x2="0" y2="1"><stop stopColor="var(--primary)" stopOpacity={.3}/><stop offset="1" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:10}}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:6}} formatter={v=>[`R$ ${Number(v).toLocaleString("pt-BR")}`,"Faturamento"]}/><Area dataKey="value" stroke="var(--primary)" strokeWidth={2} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div>}
function Dashboard({a,go}:{a:Apt[];go:(v:View)=>void}){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Faturamento hoje" value="R$ 1.280" icon={CircleDollarSign} detail="+12,4% comparado a ontem"/><Metric label="Atendimentos hoje" value="14" icon={Scissors} detail="8 concluídos · 6 na agenda"/><Metric label="Ticket médio" value="R$ 91,43" icon={WalletCards} detail="+4,2% nos últimos 30 dias"/><Metric label="Novos clientes" value="4" icon={UserRound} detail="38 novos neste mês"/></div><div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Panel><Heading title="Faturamento" sub="Últimos 7 dias"/><Chart/></Panel><Panel><Heading title="Meta mensal" sub="Setembro de 2026"/><p className="mt-8 text-3xl font-semibold">R$ 14.850</p><p className="text-xs text-muted-foreground">de R$ 20.000</p><div className="mt-6 h-2 rounded-full bg-muted"><div className="h-full w-[74.2%] rounded-full bg-primary"/></div><p className="mt-3 text-right text-sm font-semibold text-primary">74,2%</p></Panel></div><div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Panel><Heading title="Agenda de hoje" sub="Próximos atendimentos" action={<Button variant="ghost" size="sm" onClick={()=>go("agenda")}>Ver agenda <ChevronRight/></Button>}/><div className="divide-y divide-border">{a.slice(0,4).map(x=><div key={x.id} className="grid gap-2 py-3 text-sm sm:grid-cols-[55px_1fr_1fr_auto] sm:items-center"><b>{x.time}</b><div><b>{x.client}</b><p className="text-xs text-muted-foreground">{x.service}</p></div><p className="text-xs text-muted-foreground">com {x.barber}</p><Badge s={x.status}/></div>)}</div></Panel><Panel><Heading title="Indicadores" sub="Últimos 30 dias"/>{[["Clientes recorrentes","68%"],["Novos clientes","38"],["Cancelamentos","7"],["Não comparecimentos","3"]].map(x=><div key={x[0]} className="flex justify-between border-b border-border py-3 text-xs"><span className="text-muted-foreground">{x[0]}</span><b>{x[1]}</b></div>)}</Panel></div></div>}
function Agenda({a,onNew}:{a:Apt[];onNew:()=>void}){const[p,setP]=useState("Hoje");return <Panel><Heading title="Agenda" sub="Gerencie horários e disponibilidade." action={<Button onClick={onNew}><Plus/> Novo agendamento</Button>}/><div className="mb-5 flex rounded-md bg-muted p-1">{["Hoje","Amanhã","Semana"].map(x=><Button key={x} variant={p===x?"default":"ghost"} size="sm" onClick={()=>setP(x)}>{x}</Button>)}</div><div className="space-y-3">{a.map(x=><div key={x.id} className="grid grid-cols-[55px_1fr] gap-3"><b className="pt-4 text-xs">{x.time}</b><div className="rounded-md border border-border bg-background p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>{x.client}</b><p className="text-xs text-muted-foreground">{x.service} · {x.duration}</p></div><Badge s={x.status}/></div><p className="mt-3 text-xs text-muted-foreground">Profissional: <span className="text-foreground">{x.barber}</span></p></div></div>)}</div></Panel>}
function Clients({open,onNew}:{open:(c:Client)=>void;onNew:()=>void}){const[q,setQ]=useState("");return <Panel><Heading title="Clientes" sub="Relacionamento e histórico em um só lugar." action={<Button onClick={onNew}><Plus/> Novo cliente</Button>}/><div className="relative mb-5 max-w-sm"><Search className="absolute left-3 top-2.5"/><Input className="pl-9" placeholder="Buscar cliente" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border text-[9px] uppercase text-muted-foreground">{["Cliente","WhatsApp","Último atendimento","Frequência","Ticket médio","Status",""] .map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{clients.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())).map(c=><tr key={c.name} className="border-b border-border hover:bg-accent/30"><td className="p-3"><b>{c.name}</b></td><td className="p-3 text-muted-foreground">{c.phone}</td><td className="p-3 text-muted-foreground">{c.last}</td><td className="p-3 text-muted-foreground">{c.frequency}</td><td className="p-3">{c.ticket}</td><td className="p-3"><span className="rounded-full bg-muted px-2 py-1 text-[9px]">{c.status}</span></td><td><Button variant="ghost" size="icon" onClick={()=>open(c)}><ChevronRight/></Button></td></tr>)}</tbody></table></div></Panel>}
function CRM({open}:{open:(c:Client)=>void}){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Clientes ativos" value="286" icon={UsersRound} detail="+18 neste mês"/><Metric label="Clientes em risco" value="24" icon={TrendingUp} detail="8 precisam de atenção"/><Metric label="Clientes inativos" value="41" icon={Clock3} detail="Sem visita há 90+ dias"/><Metric label="Clientes recorrentes" value="194" icon={Sparkles} detail="68% da base ativa"/></div><Panel><Heading title="Funil de relacionamento" sub="Conversão nos últimos 90 dias"/><div className="grid gap-2 md:grid-cols-4">{[["Novos clientes","72"],["Primeiro atendimento","64"],["Clientes recorrentes","49"],["Clientes fidelizados","31"]].map((x,i)=><div key={x[0]} className="relative rounded-md bg-background p-4"><p className="text-[9px] uppercase text-muted-foreground">{x[0]}</p><p className="mt-2 text-2xl font-semibold">{x[1]}</p>{i<3&&<ChevronRight className="absolute -right-4 top-1/2 hidden text-primary md:block"/>}</div>)}</div></Panel><div className="grid gap-4 lg:grid-cols-2">{["Retorno próximo","Clientes em risco","Clientes inativos","Clientes frequentes","Novos clientes"].map((s,i)=><Panel key={s}><Heading title={s} sub={i===0?"Momento ideal para um novo agendamento":"Segmento atualizado automaticamente"}/>{clients.slice(i%3,(i%3)+2).map(c=><Button key={c.name} variant="ghost" className="mb-2 h-auto w-full justify-between bg-background py-3" onClick={()=>open(c)}><span className="text-left"><b className="block">{c.name}</b><small className="text-muted-foreground">Último corte: {i===0?"27 dias atrás":c.last} · {c.frequency}</small></span><ChevronRight/></Button>)}</Panel>)}</div></div>}
function Attend({a,start,finish}:{a:Apt[];start:(a:Apt)=>void;finish:()=>void}){return <div className="grid gap-4 xl:grid-cols-2">{a.map(x=><Panel key={x.id}><div className="flex justify-between gap-2"><div><p className="text-xs text-muted-foreground">{x.time} · {x.duration}</p><b>{x.client}</b></div><Badge s={x.status}/></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{[["Serviço",x.service],["Profissional",x.barber],["Valor",x.value],["Pagamento",x.payment]].map(y=><div key={y[0]}><p className="text-muted-foreground">{y[0]}</p><b>{y[1]}</b></div>)}</div>{x.status!=="REALIZADO"&&<div className="mt-5 flex gap-2">{x.status!=="EM ATENDIMENTO"&&<Button variant="outline" size="sm" onClick={()=>start(x)}>Iniciar</Button>}<Button size="sm" onClick={finish}>Finalizar</Button></div>}</Panel>)}</div>}
function Services({add}:{add:()=>void}){return <><div className="mb-5 flex justify-between"><p className="text-sm text-muted-foreground">8 serviços ativos</p><Button onClick={add}><Plus/> Novo serviço</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{services.map(x=><Panel key={x[0]}><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center rounded-md bg-accent text-primary"><Scissors/></span><span className="text-[9px] font-bold text-primary">ATIVO</span></div><h3 className="mt-6 font-semibold">{x[0]}</h3><div className="mt-3 flex justify-between"><b>{x[1]}</b><span className="text-xs text-muted-foreground">{x[2]}</span></div></Panel>)}</div></>}
function Team(){return <div className="grid gap-4 md:grid-cols-3">{[["Lucas","12","R$ 1.320","R$ 110","86%"],["Rafael","10","R$ 1.085","R$ 108,50","78%"],["Diego","8","R$ 795","R$ 99,38","64%"]].map(x=><Panel key={x[0]}><div className="flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-muted text-primary">{x[0][0]}</span><div><b>{x[0]}</b><p className="text-xs text-muted-foreground">Barbeiro · <span className="text-primary">Disponível</span></p></div></div><div className="mt-6 grid grid-cols-2 gap-4 text-xs">{[["Atendimentos",x[1]],["Faturamento",x[2]],["Ticket médio",x[3]],["Ocupação",x[4]]].map(y=><div key={y[0]}><p className="text-muted-foreground">{y[0]}</p><b>{y[1]}</b></div>)}</div><div className="mt-5 h-1.5 bg-muted"><div className="h-full bg-primary" style={{width:x[4]}}/></div></Panel>)}</div>}
function Reports(){const[p,setP]=useState("7 dias");return <div className="space-y-5"><div className="flex justify-end gap-1">{["Hoje","7 dias","30 dias"].map(x=><Button key={x} size="sm" variant={p===x?"default":"ghost"} onClick={()=>setP(x)}>{x}</Button>)}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Faturamento" value={p==="Hoje"?"R$ 1.280":"R$ 11.250"} icon={CircleDollarSign} detail="+12,4% sobre o período anterior"/><Metric label="Atendimentos" value="126" icon={Scissors} detail="Média de 18 por dia"/><Metric label="Ticket médio" value="R$ 91,43" icon={WalletCards} detail="+4,2% no período"/><Metric label="Clientes novos" value="38" icon={UserRound} detail="12 vieram por indicação"/><Metric label="Clientes recorrentes" value="68%" icon={UsersRound} detail="Meta: 72%"/><Metric label="Cancelamentos" value="7" icon={X} detail="5,5% dos agendamentos"/></div><Panel><Heading title="Faturamento por período" sub={p}/><Chart/></Panel></div>}
